language: node_js
node_js:
- 6.0.0
- 6.1.0
- 6.2.0
- 6.2.1
- 6.2.2
- 6.3.0
- 6.3.1
matrix:
  fast_finish: true
branches:
  only: master
git:
  depth: 2
before_deploy:
- openssl aes-256-cbc -K $encrypted_4ad9e6c1e3a9_key -iv $encrypted_4ad9e6c1e3a9_iv
  -in travis_rsa.enc -out travis_rsa -d
- bin/travis/github_auth
