language: node_js
node_js:
  - 6.0.0
  - 6.1.0
  - 6.2.0
  - 6.2.1
  - 6.2.2
  - 6.3.0
matrix:
  fast_finish: true
branches:
  only: master
git:
  depth: 2
cache:
  directories:
    - node_modules
install:
  - npm install
  - npm prune
script:
  - npm run test:all
deploy:
  provider: npm
  email: ivo.putzer@gmail.com
  # skip_cleanup: true
  api_key: $NPM_API_KEY
# before_deploy: bin/travis/before_deploy
# after_deploy: bin/travis/after_deploy
